### ISSUE TITLE
Unable to configure System startup ConfigTool

### ISSUE THREAD

**Issue by sburdka** [devdnl/dnx-rtos#1]
I am unable to configure system startup while running config tool. No option has been seen on it. Is it removed from dnx-rtos project?
![screenshot from 2018-03-09 14 04 33](https://user-images.githubusercontent.com/2720538/37198025-dc5ad034-23a2-11e8-9347-d736c936d10e.png)

**Comment by devdnl** [comment]
System startup you should code by your own by using initd program. In this tool you can setup hardware and some specific modules options.
